//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFapp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFapp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad.
        /// </summary>
        internal static string btnBack_Content {
            get {
                return ResourceManager.GetString("btnBack.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        internal static string btnCroatian_Content {
            get {
                return ResourceManager.GetString("btnCroatian.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engleski.
        /// </summary>
        internal static string btnEnglish_Content {
            get {
                return ResourceManager.GetString("btnEnglish.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        internal static string btnExit_Content {
            get {
                return ResourceManager.GetString("btnExit.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žensko.
        /// </summary>
        internal static string btnFemale_Content {
            get {
                return ResourceManager.GetString("btnFemale.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muško.
        /// </summary>
        internal static string btnMale_Content {
            get {
                return ResourceManager.GetString("btnMale.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sljedeće.
        /// </summary>
        internal static string btnNext_Content {
            get {
                return ResourceManager.GetString("btnNext.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite željeno prvenstvo:.
        /// </summary>
        internal static string lblGender_Content {
            get {
                return ResourceManager.GetString("lblGender.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite jezik:.
        /// </summary>
        internal static string lblLanguage_Content {
            get {
                return ResourceManager.GetString("lblLanguage.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odaberite reprezentaciju:.
        /// </summary>
        internal static string lblNationalTeam_Content {
            get {
                return ResourceManager.GetString("lblNationalTeam.Content", resourceCulture);
            }
        }
    }
}
